version: '3.9'

services:
  web:
    build: .
    command: bash -c "python main.py"
    environment:
      - IPDATA_API_KEY=test
      - AUTH_JWT_SECRET_KEY=test
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=mysql_db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_HOST=db
      - MYSQL_PORT=3307
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql_data:

