version: '3.9'

services:
  web:
    build: .
    command: bash -c "python main.py"
    environment:
      - IPDATA_API_KEY=test
      - AUTH_JWT_SECRET_KEY=secret
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq


  worker:
    build: .
    command: bash -c "celery -A celery_worker worker -l info"
    depends_on:
      - db
      - rabbitmq


  db:
    image: mysql:latest
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=mysql_db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_HOST=db
      - MYSQL_PORT=3307
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql/


  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
      - RABBITMQ_PORT=5672
    ports:
      - "5672:5672"
    volumes:
      - /var/lib/rabbitmq/
      - /var/log/rabbitmq/


  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1


volumes:
  mysql_data:
